module.exports = {
	printWidth: 80,
	tabWidth: 4,
	useTabs: true,
	semi: true,
	singleQuote: false,
	quoteProps: "as-needed",
	jsxSingleQuote: false,
	trailingComma: "all",
	bracketSpacing: true,
	bracketSameLine: true,
	jsxBracketSameLine: true,
	arrowParens: "always",
	endOfLine: "crlf",
	singleAttributePerLine: false,
};
