export const services = [
	{
		size: 'max-w-xs',
        image: require('../../assets/Homepage/eCommerce.png'),
        altText: 'Comércio Digital',
        title: 'Comércio Digital',
        subTitle: 'Pretende vender on-line?',
        text: 'Implementamos soluções eCommerce B2C, eCommerce B2B, Order Management System, Headless Commerce e Live eCommerce Stream.',
        urlTitle: 'Saber mais',
        internalHref: 'solucoes/comercio-digital',
	},
	{
		size: 'max-w-xs',
        image: require('../../assets/Homepage/MarketingPerformance.png'),
        altText: 'Marketing Digital e Performance',
        title: 'Marketing Digital e Performance',
        subTitle: 'Procura impulsionar o seu negócio?',
        text: 'Somos focados em Estratégia Digital, Design e Gestão de Redes Sociais, Performance e E-mail Marketing, Consultoria e Advising Digital.',
        urlTitle: 'Saber mais',
        internalHref: 'solucoes/marketing-digital-performance',
	},
	{
		size: 'max-w-xs',
        image: require('../../assets/Homepage/UIUxDesign.png'),
        altText: 'UI/UX Design',
        title: 'UI/UX Design',
        subTitle: 'Pretende proporcionar uma melhor experiência?',
        text: 'Somos focados em melhorar a experiência de produtos e serviços digitais, trazendo resultados incríveis para o negócio.',
        urlTitle: 'Saber mais',
        internalHref: 'solucoes/uiux-design',
	},
	{
		size: 'max-w-xs',
        image: require('../../assets/Homepage/Software,CRM,Data.png'),
        altText: 'Web Development',
        title: 'Web Development',
        subTitle: 'Faz tarefas manualmente?',
        text: 'Otimize processos, acelere a transformação digital e desenhe novas experiências, tirand melhor partido da tecnologia, obtendo dados em tempo real.',
        urlTitle: 'Saber mais',
        internalHref: 'solucoes/web-development',
	},
];